### ISSUE TITLE
Flagged by several antiviruses

### ISSUE THREAD

**Issue by RuinTD** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#2]
Hello. Just so you know, the Windows download for your application is being detected by Windows Defender and a few other anti-viruses, as can be seen here on VirusTotal:
https://www.virustotal.com/gui/file/48c4577490b0c5f482acea19880093f7cbb81d783acee4e7b82c4d5e6b79acbb/detection

I have already submitted the file to Microsoft for analysis. You can also submit it yourself as the software developer here:
https://www.microsoft.com/en-us/wdsi/filesubmission

In the meantime, I might recommend making a note in the readme mentioning this, suggesting users manually review the source and run it directly with python if skeptical.

**Comment by Gust4Oliveira** [comment]
Thanks for notifying this issue, i'll send a report of false positive to Microsoft as well and also to the other antivirus softwares that detect the app as a virus.

For now i'll keep the issue opened until the false detection problem is gone and add the suggested info on the readme.

**Comment by RuinTD** [comment]
> ![image](https://user-images.githubusercontent.com/1149870/94984129-0d89a800-0506-11eb-84c4-82f3b43b9d56.png)

The file has been analyzed by Microsoft and is no longer being detected. However, after reanalyzing the file on VirusTotal (same link from the original post), it looks like 4 additional antiviruses are flagging the program now, of note being McAfee (does anyone still use McAfee?).

**Comment by Gust4Oliveira** [comment]
Update: 
Now, according to VirusTotal, only four anti-virus softwares are flagging the application as a malware: https://www.virustotal.com/gui/file/48c4577490b0c5f482acea19880093f7cbb81d783acee4e7b82c4d5e6b79acbb/detection
I'm sending now a false alarm report to Cyren and McAfee, to IKARUS is only possible to send a false report if i use the software, so if someone use it and face the warning, feel free to send it to analysis. And last, i didn't find any way to contact Jiangmin developer since is a engine used by chinese enterprise anti-virus softwares, i don't think that anyone will face problems with it.

**Comment by Gust4Oliveira** [comment]
With the v.1.1.1 release all flags returned, i give up. This issue will haunt the app until a definitive version be released. I'll keep the issue open and the disclaimer as well.
