### ISSUE TITLE
Doesn't show the actual song artist

### ISSUE THREAD

**Issue by flickur** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#3]
Hi,

Noticed the script only shows song title and _album_ artist + album. Often times be it a collaboration album etc. the album artist is not the same as song artist which results in misleading info.

**Comment by Gust4Oliveira** [comment]
Hello, all right, i understand the problem that you are facing, it can be related to some misleading information on the song metadata at last.fm but i have to check it. Can you provide me a album that you notice this behavior so i can analize it and seek for a fix?

**Comment by flickur** [comment]
It happens with every song where album artist is different to song artist. "Dash Berlin - United Destination 2010" for example is the album i'm listening to now.

**Comment by Gust4Oliveira** [comment]
Okay, i'll take a look.

**Comment by Gust4Oliveira** [comment]
I tried to reproduce the problem using spotify and the album that you mentioned. I didn't face the issue you mentioned, but the artist info isn't complete, only the first artist of the track is showed. As you can see on the following images:
![image](https://user-images.githubusercontent.com/43550940/105648043-1d980f80-5e88-11eb-88f9-a13e8add192c.png)
![image](https://user-images.githubusercontent.com/43550940/105648085-5b953380-5e88-11eb-8493-7228cbae6bc7.png)
This happened due to incomplete metadata of the track on Spotify servers, on front end we see all artists, but the song it self doesn't have this data, this is pretty common using spotify. 

Trying again with the same album but local, i didn't faced the issue. Please check if in your profile at last.fm the tracks scrobbled are with the same behaviour, if yes, there is a problem on the scrobbler that you are using or with the metadata of your songs.

**Comment by flickur** [comment]
Listening local files with foobar, metadata is correct and it's fine on last.fm. Here is my track metadata:
![image](https://user-images.githubusercontent.com/40724723/105764863-35db5d80-5f60-11eb-960e-ed2b3fcb114d.png)

here's how it's on last.fm
![image](https://user-images.githubusercontent.com/40724723/105764937-51deff00-5f60-11eb-99b1-5bd2efd240d3.png)

and here's how it's on discord
![image](https://user-images.githubusercontent.com/40724723/105765055-7a66f900-5f60-11eb-831e-34195e59c168.png)

as you can see it's missing the song artist on the discord rich presence.

**Comment by Gust4Oliveira** [comment]
All right, i checked the lastfm library used and i didn't find any alternative to get the artist and avoid this behaviour, unfortunately thats beyond the script and hould need changes in the library if last.fm provides any alternative in their API. Right now the app uses Pylast library, the recommended API from last.fm it self for python.
